name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      
    - name: Publish
      run: dotnet publish --no-build src/Aoraki.Web/Aoraki.Web.csproj -c Release -o aoraki

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: aoraki
        path: aoraki/**
        if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: PROD
      url: ${{ steps.deployapp.outputs.webapp-url }}
      
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: aoraki
        path: aoraki
        
    - name: Authenticate
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy app
      id: deployapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: aoraki-8acf69
        package: aoraki
        
    - name: Logout
      run: az logout
